POST http://localhost:11004/api/rs/supervisor/procedure/submit
Content-Type: application/json

{
  "requestId": "REQ_2",
  "namespace": "mars_cluster_dev",
  "supervisorId": "mars_master_1",
  "taskName": "Consistencier_RunJob",
  "skillRequirement": "Consistencier",
  "principle": {
    "dispatcherName": "ShortestQueue",
    "dispatchType": "Allocate"
  },
  "args": {
    "py": "123"
  }
}

###
